name: models
description: A starting point for Dart libraries or applications.
version: 23.09.22+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  intl: ^0.18.1
  utils:

dev_dependencies:
  lints: ^2.0.0
