name: models
description: A starting point for Dart libraries or applications.
version: 23.09.28+1

environment:
  sdk: ^3.1.1

dependencies:
  intl: ^0.18.1
  universal_html: ^2.2.4
  utils:

dev_dependencies:
  lints: ^2.0.0
