name: models
description: A starting point for Dart libraries or applications.
version: 24.05.30+2

environment:
  sdk: ^3.2.0

dependencies:
  intl: ^0.18.1
  universal_html: ^2.2.4
  utils:

dev_dependencies:
  lints: ^2.0.0
