name: cron_scheduler
description: A sample command-line application.
version: 24.06.10+1

environment:
  sdk: ">=2.18.4 <=3.3.1"

dependencies:
  cron: ^0.5.1
  http_client:
  utils:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
