name: cron_scheduler
description: A sample command-line application.
version: 24.05.23+2

environment:
  sdk: ">=2.18.4 <=3.2.0"

dependencies:
  cron: ^0.5.1
  http_client:
  utils:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
