name: forgottenland
description: forgottenland

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 24.06.02+5

environment:
  sdk: ">=2.17.0 <=3.2.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.0
  dropdown_search: ^5.0.6
  url_launcher: ^6.0.10
  flutter_svg: ^1.1.6
  intl: ^0.18.1
  device_info_plus: ^8.1.0
  get: ^4.6.5
  models:
  utils:
  http_client:
  database_client:
  package_info_plus: ^3.1.2
  firebase_core: ^2.16.0
  firebase_analytics: ^10.5.0
  firebase_crashlytics: ^3.4.5
  font_awesome_flutter: ^10.5.0
  firebase_performance: ^0.9.3+5
  crypto: ^3.0.3
  shared_preferences: ^2.2.3
  hovering: ^1.0.4

dev_dependencies:
  flutter_launcher_icons: ^0.12.0
  lint: ^2.1.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true
  web:
    generate: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/icons/battleye_type/
    - assets/icons/location/
    - assets/icons/news_type/
    - assets/icons/pvp_type/
    - assets/icons/rank/
    - assets/images/
    - assets/images/background/
    - assets/images/sponsor/
    - assets/outfit/
    - assets/svg/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MartianMono
      fonts:
        - asset: assets/fonts/MartianMono/MartianMono.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
