name: forgottenland
description: forgottenland

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.0
  dio: ^5.1.1
  dropdown_search: ^3.0.1
  font_awesome_flutter: ^10.1.0
  url_launcher_web: ^2.0.4
  url_launcher: ^6.0.10
  material_design_icons_flutter: ^6.0.7096
  supabase_flutter: ^1.2.2
  flutter_svg: ^1.1.6
  intl: ^0.18.0
  device_info_plus: ^8.1.0
  get: ^4.6.5
  models:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0
  lint: ^2.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true
  web:
    generate: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.jpg
    - assets/logo_alt.png
    - assets/scroll.png
    - assets/outfit/awkn.png
    - assets/outfit/draven.png
    - assets/outfit/karkaroff.png
    - assets/outfit/junck.png
    - assets/outfit/freedan.png
    # icons:
    - assets/icons/rank/rank1.png
    - assets/icons/rank/rank2.png
    - assets/icons/rank/rank3.png
    - assets/icons/rank/rank4.png
    - assets/icons/rank/globalrank1.png
    - assets/icons/rank/globalrank2.png
    - assets/icons/rank/globalrank3.png
    - assets/icons/rank/globalrank4.png
    - assets/icons/battleye_type/yellow.png
    - assets/icons/battleye_type/green.png
    - assets/icons/battleye_type/none.png
    - assets/icons/pvp_type/optional_pvp.png
    - assets/icons/pvp_type/open_pvp.png
    - assets/icons/pvp_type/hardcore_pvp.png
    - assets/icons/pvp_type/retro_open_pvp.png
    - assets/icons/pvp_type/retro_hardcore_pvp.png
    - assets/icons/news_type/cipsoft.png
    - assets/icons/news_type/community.png
    - assets/icons/news_type/development.png
    - assets/icons/news_type/support.png
    - assets/icons/news_type/technical.png
    # images
    - assets/images/background/25th_anniversary.jpg
    - assets/images/background/offline.jpg
    # svg
    - assets/svg/logo.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/RobotoSlab/RobotoSlab_Regular.ttf
        - asset: assets/fonts/RobotoSlab/RobotoSlab_Bold.ttf
        - asset: assets/fonts/RobotoSlab/RobotoSlab_Thin.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
