name: forgottenland
description: forgottenland

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 24.05.23+2

environment:
  sdk: ">=2.17.0 <=3.2.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.0
  dropdown_search: ^5.0.6
  url_launcher: ^6.0.10
  flutter_svg: ^1.1.6
  intl: ^0.18.1
  device_info_plus: ^8.1.0
  get: ^4.6.5
  models:
  utils:
  http_client:
  database_client:
  package_info_plus: ^3.1.2
  firebase_core: ^2.16.0
  firebase_analytics: ^10.5.0
  firebase_crashlytics: ^3.4.5
  font_awesome_flutter: ^10.5.0
  firebase_performance: ^0.9.3+5

dev_dependencies:
  flutter_launcher_icons: ^0.12.0
  lint: ^2.1.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true
  web:
    generate: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/battleye_type/green.png
    - assets/icons/battleye_type/none.png
    - assets/icons/battleye_type/yellow.png
    - assets/icons/location/EU.svg
    - assets/icons/location/NA.svg
    - assets/icons/location/SA.svg
    - assets/icons/news_type/cipsoft.png
    - assets/icons/news_type/community.png
    - assets/icons/news_type/development.png
    - assets/icons/news_type/support.png
    - assets/icons/news_type/technical.png
    - assets/icons/pvp_type/hardcore_pvp.png
    - assets/icons/pvp_type/open_pvp.png
    - assets/icons/pvp_type/optional_pvp.png
    - assets/icons/pvp_type/retro_hardcore_pvp.png
    - assets/icons/pvp_type/retro_open_pvp.png
    - assets/icons/rank/globalrank1.png
    - assets/icons/rank/globalrank2.png
    - assets/icons/rank/globalrank3.png
    - assets/icons/rank/globalrank4.png
    - assets/icons/rank/rank1.png
    - assets/icons/rank/rank2.png
    - assets/icons/rank/rank3.png
    - assets/icons/rank/rank4.png
    - assets/icons/tibia_coin_trusted.png
    - assets/images/background/25th_anniversary.jpg
    - assets/images/background/offline.jpg
    - assets/images/splash/tintas_merighi.jpeg
    - assets/logo_alt.png
    - assets/logo.jpg
    - assets/outfit/awkn.png
    - assets/outfit/draven.png
    - assets/outfit/junck.png
    - assets/outfit/karkaroff.png
    - assets/scroll.png
    - assets/svg/logo.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MartianMono
      fonts:
        - asset: assets/fonts/MartianMono/MartianMono.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
