name: http_client
description: A starting point for Dart libraries or applications.
version: 24.03.29+1

environment:
  sdk: '>=3.1.1'

dependencies:
  dio: ^5.1.1
  utils:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
