name: forgottenlandetl
description: A server app using the shelf package and Docker.
version: 23.09.28+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  args: ^2.0.0
  database_client:
  http_client:
  models:
  shelf_router: ^1.0.0
  shelf: ^1.1.0
  universal_html: ^2.2.4
  utils:


dev_dependencies:
  build_runner: ^2.3.2
  build_web_compilers: ^3.2.7
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.15.0
