name: utils
description: A starting point for Dart libraries or applications.
version: 24.06.03+1

environment:
  sdk: ">=3.2.0"

dependencies:
  dotenv: ^4.1.0
  models:
  shelf: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
