name: utils
description: A starting point for Dart libraries or applications.
version: 23.09.20+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  dotenv: ^4.1.0
  models:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
