name: utils
description: A starting point for Dart libraries or applications.
version: 23.05.09+1
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  models:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
