name: forgottenlandapi
description: A server app using the shelf package and Docker.
version: 23.09.17+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  args: ^2.0.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  models:
  utils:
  http_client:
  database_client:

dev_dependencies:
  build_runner: ^2.3.2
  build_web_compilers: ^3.2.7
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.15.0
