name: database_client
description: A starting point for Dart libraries or applications.
version: 23.09.11+4

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  postgrest: ^2.1.0
  supabase: ^2.0.7

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
