name: database_client
description: A starting point for Dart libraries or applications.
version: 24.06.10+1

environment:
  sdk: ">=2.18.4 <=3.3.1"

dependencies:
  postgrest: ^2.1.0
  supabase: ^2.0.7

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
