name: database_client
description: A starting point for Dart libraries or applications.
version: 24.05.23+2

environment:
  sdk: ">=2.18.4 <=3.2.0"

dependencies:
  postgrest: ^2.1.0
  supabase: ^2.0.7

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
